[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173  # Default Vite dev server port
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
